In [ ]:
import numpy as np

TRANSLATION_VECTOR = np.array([-1, 0])

ROTATION_ANGLE_DEGREES = 45

# HINWEIS: Die Reihenfolge hier ist die REIHENFOLGE DER MULTIPLIKATION (von links nach rechts),
SEQUENCE = ["T_inv", "MirrorY" ,"Rotate", "T"]

def get_translation_matrix(vector):
    tx, ty = vector
    return np.array([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0,  1]
    ])

def get_rotation_matrix(degrees):
    rad = np.deg2rad(degrees)
    c = np.cos(rad)
    s = np.sin(rad)
    return np.array([
        [c, -s, 0],
        [s,  c, 0],
        [0,  0, 1]
    ])

def get_mirror_x_matrix():
    return np.array([
        [1,  0, 0],
        [0, -1, 0],
        [0,  0, 1]
    ])

def get_mirror_y_matrix():
    return np.array([
        [-1, 0, 0],
        [ 0, 1, 0],
        [ 0, 0, 1]
    ])

def run_transformation_chain():
    individual_matrices = []

    # Die Abfolge von links nach rechts durchgehen, um die Matrizen zu generieren
    for op_name in SEQUENCE:
        matrix = None
        description = ""

        if op_name == 'T':
            matrix = get_translation_matrix(TRANSLATION_VECTOR)
            description = f"Matrix für Translation T({TRANSLATION_VECTOR[0]}, {TRANSLATION_VECTOR[1]})"
        elif op_name == 'T_inv':
            matrix = get_translation_matrix(-TRANSLATION_VECTOR)
            description = f"Matrix für Rück-Translation T({-TRANSLATION_VECTOR[0]}, {-TRANSLATION_VECTOR[1]})"
        elif op_name == 'Rotate':
            matrix = get_rotation_matrix(ROTATION_ANGLE_DEGREES)
            description = f"Matrix für Rotation R({ROTATION_ANGLE_DEGREES}°)"
        elif op_name == 'MirrorX':
            matrix = get_mirror_x_matrix()
            description = "Matrix für Spiegelung an der x-Achse"
        elif op_name == 'MirrorY':
            matrix = get_mirror_y_matrix()
            description = "Matrix für Spiegelung an der y-Achse"
        else:
            print(f"WARNUNG: Unbekannte Operation '{op_name}' wird übersprungen.")
            continue

        print(description)

        # Ausgabe mit Lösungsweg
        if op_name == 'Rotate':
            angle_str = str(ROTATION_ANGLE_DEGREES)
            symbolic_matrix_str = (
                f"[[ cos({angle_str}°), -sin({angle_str}°), 0 ],\n"
                f" [ sin({angle_str}°),  cos({angle_str}°), 0 ],\n"
                f" [   0    ,    0    , 1 ]]"
            )
            print(symbolic_matrix_str, "\n")
        else:
            print(np.round(matrix, 3), "\n")

        individual_matrices.append(matrix)

    if not individual_matrices:
        print("Keine Operationen durchgeführt.")
        return

    final_matrix = np.linalg.multi_dot(individual_matrices)

    print("-" * 60)

    print("GESAMTERGEBNIS\n")
    print("Die Gesamttransformationsmatrix lautet:")
    print(np.round(final_matrix, 3))
    print("\nDiese Matrix führt alle definierten Schritte in einer einzigen Operation aus.")


if __name__ == "__main__":
    run_transformation_chain()


Starte die Berechnung der Transformationskette...
Definierte Multiplikations-Reihenfolge: ['T_inv', 'MirrorY', 'Rotate', 'T']

------------------------------------------------------------
Matrix für Rück-Translation T(1, 0)
[[1 0 1]
 [0 1 0]
 [0 0 1]] 

Matrix für Spiegelung an der y-Achse
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  1]] 

Matrix für Rotation R(45°)
[[ cos(45°), -sin(45°), 0 ],
 [ sin(45°),  cos(45°), 0 ],
 [   0    ,    0    , 1 ]] 

Matrix für Translation T(-1, 0)
[[ 1  0 -1]
 [ 0  1  0]
 [ 0  0  1]] 

------------------------------------------------------------
GESAMTERGEBNIS

Die Gesamttransformationsmatrix (Ergebnis der Multiplikation aller Matrizen) lautet:
[[-0.707  0.707  1.707]
 [ 0.707  0.707 -0.707]
 [ 0.     0.     1.   ]]

Diese Matrix führt alle definierten Schritte in einer einzigen Operation aus.
